version: '3.1'

services:
    build:
        build:
            context: .
            dockerfile: Dockerfile.environment
        volumes:
         - .:/code
        working_dir: /code
        user: llvm
        command: ./build.sh
    benchmark:
        build:
            context: .
            dockerfile: Dockerfile.environment
        volumes:
         - .:/code
        working_dir: /code/benchmarks
        user: llvm
        command: ./run_all_benchmarks.sh
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile.environment
        volumes:
         - .:/code
        working_dir: /code
        user: llvm
        command: ./build_node.sh
    firefox:
        image: firefox-env
        volumes:
         - .:/code
        working_dir: /code
        user: llvm
        command: ./build_firefox.sh
    firefox-bash:
        image: firefox-env
        volumes:
         - .:/code
        working_dir: /code
        user: root
        command: /bin/bash
        tty: true
        stdin_open: true
    bash_llvm:
        build:
            context: .
            dockerfile: Dockerfile.environment
        volumes:
         - .:/code
        working_dir: /code/benchmarks
        user: llvm
        stdin_open: true
        tty: true
        command: /bin/bash
    bash:
        build:
            context: .
            dockerfile: Dockerfile.environment
        volumes:
         - .:/code
        working_dir: /code/benchmarks
        user: root
        stdin_open: true
        tty: true
        command: /bin/bash
