#!/bin/bash
set -e
XARGS="-flto -fsanitize=hextype -femit-ivtbl -femit-cast-checks -Wl,-plugin=/code/build/lib/LLVMgold.so -Wl,-plugin-opt=save-temps -Wl,-plugin-opt=sd-ivtbl"
for arg in "$@"; do
  case "$arg" in
  -c|-E|-V)
    XARGS=""
    ;;
  -shared)
	XARGS="-flto -fsanitize=hextype -femit-ivtbl -femit-cast-checks -Wl,-plugin=/code/build/lib/LLVMgold.so -Wl,-plugin-opt=save-temps -Wl,-plugin-opt=sd-ivtbl"
    ;;
  esac
done
/code/build/bin/clang++ "$@" $XARGS
